Repository pulumi/pulumi-dotnet, pull requests merged in 2023-01, with the labels that each got.

#70 Patch use of set-output
  .github/scripts/set-output
  .github/workflows/on-release.yml
  .github/workflows/release-dotnet-provider.yml
Labels: impact/no-changelog-required

#75 Add tests with solution files
  integration_tests/integration_dotnet_test.go
  integration_tests/integration_util_test.go
  integration_tests/sln/.gitignore
  integration_tests/sln/Program.cs
  integration_tests/sln/Pulumi.yaml
  integration_tests/sln/Sln.csproj
  integration_tests/sln/Sln.sln
  integration_tests/sln_multiple_nested/.gitignore
  integration_tests/sln_multiple_nested/Library/Libary.csproj
  integration_tests/sln_multiple_nested/Library/Program.cs
  integration_tests/sln_multiple_nested/Program/Program.cs
  integration_tests/sln_multiple_nested/Program/Program.csproj
  integration_tests/sln_multiple_nested/Pulumi.yaml
  integration_tests/sln_multiple_nested/Sln.sln
Labels: impact/no-changelog-required

#80 [sdk] Delegates alias computation to engine
  CHANGELOG.md
  CHANGELOG_PENDING.md
  sdk/Pulumi.Tests/Mocks/Aliases.cs
  sdk/Pulumi.Tests/Mocks/MocksTests.cs
  sdk/Pulumi/Deployment/Deployment.cs
  sdk/Pulumi/Deployment/Deployment_Prepare.cs
  sdk/Pulumi/Deployment/Deployment_RegisterResource.cs
  sdk/Pulumi/Pulumi.xml
  sdk/Pulumi/Resources/Resource.cs
Labels: kind/enhancement

#78 Add a test for the DeletedWith resource option
  .github/workflows/pr.yml
  integration_tests/deleted_with/.gitignore
  integration_tests/deleted_with/DeletedWith.csproj
  integration_tests/deleted_with/FailsOnDelete.cs
  integration_tests/deleted_with/MyStack.cs
  integration_tests/deleted_with/Program.cs
  integration_tests/deleted_with/Pulumi.yaml
  integration_tests/deleted_with/Random.cs
  integration_tests/integration_dotnet_test.go
  integration_tests/testprovider/TestProvider.cs
Labels: impact/no-changelog-required

#86 Run tests on the production service
  .github/workflows/pr.yml
  .github/workflows/release-sdk.yml
Labels: impact/no-changelog-required

#88 [sdk] Correctly check for alias support in the engine and map fully specified alias urns
  CHANGELOG_PENDING.md
  sdk/Pulumi/Deployment/Deployment.cs
  sdk/Pulumi/Deployment/Deployment_Prepare.cs
Labels: kind/bug

#94 [sdk] Bring back the correct fallback behavior for calculating aliases for older Pulumi engines
  CHANGELOG_PENDING.md
  sdk/Pulumi/Deployment/Deployment_Prepare.cs
  sdk/Pulumi/Deployment/Deployment_RegisterResource.cs
  sdk/Pulumi/Pulumi.xml
  sdk/Pulumi/Resources/Resource.cs
Labels: kind/bug

#95 Reset CHANGELOG post release
  CHANGELOG.md
  CHANGELOG_PENDING.md
Labels: impact/no-changelog-required

#97 [sdk] Lazily initialize alias combinations during `RegisterResourceRequest` preparation
  CHANGELOG_PENDING.md
  sdk/Pulumi.Tests/Mocks/Aliases.cs
  sdk/Pulumi.Tests/Mocks/MocksTests.cs
  sdk/Pulumi/Deployment/Deployment_Prepare.cs
  sdk/Pulumi/Pulumi.xml
  sdk/Pulumi/Resources/Resource.cs
Labels: kind/enhancement
