Repository pulumi/pulumi-dotnet, pull requests merged in 2024-01, with the labels that each got.

#222 ci: Use GITHUB_OUTPUT envvar instead of set-output command
  .github/workflows/release-dotnet-provider.yml
Labels: impact/no-changelog-required

#227 Run build & test steps on windows & macos if the ci/test label is set
  .github/workflows/pr.yml
Labels: impact/no-changelog-required, ci/test

#226 [auto] Add new API to install the Pulumi CLI from the Automation API
  .changes/unreleased/Improvements-226.yaml
  build/Program.fs
  sdk/Pulumi.Automation.Tests/LocalPulumiCmdTests.cs
  sdk/Pulumi.Automation.Tests/LocalPulumiCommandTests.cs
  sdk/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
  sdk/Pulumi.Automation/Commands/CommandResult.cs
  sdk/Pulumi.Automation/Commands/LocalPulumiCmd.cs
  sdk/Pulumi.Automation/Commands/LocalPulumiCommand.cs
  sdk/Pulumi.Automation/Commands/PulumiCommand.cs
  sdk/Pulumi.Automation/LocalWorkspace.cs
  sdk/Pulumi.Automation/LocalWorkspaceOptions.cs
  sdk/Pulumi.Automation/Pulumi.Automation.csproj
  sdk/Pulumi.Automation/PulumiSdkVersionAttribute.cs
  sdk/Pulumi.Automation/RemoteWorkspace.cs
  sdk/Pulumi.Automation/Workspace.cs
Labels: ci/test
